[build]
  publish = "_site"
  command = "eleventy"
  functions = "functions/"
# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

# [[redirects]]
#   from = "/*"
#   to = "https://test.co/:splat"
#   status = 200
#   force = true
#   [redirects.headers]
#     Access-Control-Allow-Origin = "*"

# [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  # for = "/*"
  # [headers.values]
  #   Access-Control-Allow-Origin = "*"



#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
